### ISSUE TITLE
isue nummer 6 not solved

### ISSUE THREAD

**Issue by esszopo** [ajf8/mcomaster#11]
hi,
i've changed 2 things because mcollect has type number and type integer fields
line 35
     switch actionDdl.input[ddlKey].type
        when "string" then actionDdl.input[ddlKey]['isString'] = 1
        when "boolean" then actionDdl.input[ddlKey]['isBool'] = 1
        when "number", "integer"
          actionDdl.input[ddlKey]['isInteger'] = 1
          validationRules[ddlKey] = {
            remote : {
              type : "POST"
              dataType : "number"
              url : "/ddls/"+agent+"/validate/"+action
            }
          }
line 88 
      if input_type == "boolean"
        if x.value == "true"
          x.value = true
        else
          x.value = false
      else if input_type in ["integer","number"]
        x.value = parseInt(x.value)

**Comment by ajf8** [comment]
Thanks for this and the other reports. I'm about to go on holiday for a 
few days, but will apply this and take a look at your other reports next 
week.

Regards,
Alan

**Comment by ajf8** [comment]
I've commited this, thanks. I made a small change, so that the dataType is placed into the existing validation hash instead recreating it.
