### ISSUE TITLE
when loggin in I first have to logout.

### ISSUE THREAD

**Issue by esszopo** [ajf8/mcomaster#16]
After I log in I have to log out as the first thing i do, because if I don't I will not get any response. 
When I do that I don't get logged out but a rebuild of the display starts and I can start working with the tool. It's annoying but I can live with it.

**Comment by esszopo** [comment]
Just an update I found out that a reload of the first page does the trick too

**Comment by ajf8** [comment]
Can you take a look what's happening in chrome developer tools / firebug? Mainly network requests that are failing.

There's some javascript which detects 403's and if any are found you get sent to the login page. I've seen similar issues where you're not actually logged out, but the rails CSRF token validation fails.
