### ISSUE TITLE
tool doesn't allow me to log in using windows internet explorer.

### ISSUE THREAD

**Issue by esszopo** [ajf8/mcomaster#17]
It just will not accept any password/user I use.

**Comment by ajf8** [comment]
I tried it on IE9 on Win7, and was surprised that it seems to work fine, since I don't remember ever testing in IE.

Any errors in the IE developer tools console? or anything that looks weird in the login request? The IE dev tools are quite nice these days.

**Comment by esszopo** [comment]
I think it's a IE8 problem. Win7 and IE8 nologin, On windows server 2003R2 login once after that I get the message I've to login first before continuing while trying to login.
