### ISSUE TITLE
issue with service agent

### ISSUE THREAD

**Issue by sentinelleader** [ajf8/mcomaster#2]
Hi,

The rpcutil and process agents are working fine. But when i try to use the service agent plugin, it shows me an error "Cannot validate input service: Unknown validator: 'service_name'.". Infact when i start typing in the service name box, a popup is is showing this error, when i click on execute, the same error shows up in the result section also.

My mcollective-client and mcomaster resides in the same machine

**Comment by ajf8** [comment]
Hi,

You are probably missing the validator directory from the service plugin tree, it needs to go into your mcollective libdir along with the agent. I had the same problem.

https://github.com/puppetlabs/mcollective-service-agent/tree/master/validator

**Comment by sentinelleader** [comment]
mmm both the files service_name.ddl, service_name.rb  are available in my validator directory

**Comment by sentinelleader** [comment]
Strange to say it started working fine now.  Thanks for the reply, i'm using mysql as the backend, it would nice if you can add the mysql gem also in the Gemfile. 

Regards
Deepak

**Comment by ajf8** [comment]
Cool. What kind of backend? for discovery?

**Comment by sentinelleader** [comment]
Nop for the mcomaster rails app as the database :-)

**Comment by ajf8** [comment]
Ah of course, that's good to know, as I've only tried with sqlite so far (though didn't expect any issues).

I'll have a look how best to do optional dependencies in the Gemfile some time.

**Comment by sentinelleader** [comment]
Cool.  Works fine with mysql also :-) 

Alan F notifications@github.com wrote:

> Ah of course, that's good to know, as I've only tried with sqlite so
> far (though didn't expect any issues).
> 
> I'll have a look how best to do optional dependencies in the Gemfile
> some time.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ajf8/mcomaster/issues/2#issuecomment-18151467

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.
