### ISSUE TITLE
Questions about mcomaster install documentation

### ISSUE THREAD

**Issue by stellatian** [ajf8/mcomaster#24]
Hi,

I already have installed MCollective and it is working fine. Now I plan to use Mcomaster as a Web UI.

The install documentation on this web site is pretty clear:
http://www.mcomaster.org/docs/install

But I still have several questions:
1. In "Prerequisites",  it mentions Ruby 1.9, Redis database and Bundler. Later it explains that "The el6 mcomaster RPM currently bundles all of its rubygem dependencies". Does this mean it contains all (ruby 1.9, Redis database and Bundler)?   It mentions Ruby 1.9 explicitly, so I am pretty that I don't need to install Ruby 1.9 by myself, but not very sure about Redis database and Bundler? Do I need to install them by myself? If yes, how?  "gem install redis" and "gem install bundler"? The install doc doesn't mention the detail.
2. In "Setup mcollective", it says, "NOTE: you will need to make sure the redis gem is available to the ruby which is running this mcollective". Does this mean I need to configure something additional or it is just a note that explains this step (Configure the host, port and DB number for the registration agent (server.cfg))?
3.  In "Setup mcollective", it says, "And add the following settings to the client.cfg. The setting names are the same as are used in server.cfg. You only need to do this in the client.yml on the host running mcomaster". Why does it mention client.yml? Do you mean client.cfg? Confused.
4. After mcomaster is installed and started, what is the UI and port to log on? http://localhost:3000? But port 3000 is already used by Puppet Dashboard, right? Will it replace Dashbard? I thought Dashboard UI and Mcollective UI (here, mcomaster) are different UIs.

Thanks a lot!

Stella

**Comment by stellatian** [comment]
NOTE: Alan and I also used google mcollective user group to discuss this issue, so I will copy his reply over.

---

From Alan: 
Hi there!

I'll get back to you shortly with answers to the below questions.

But if you want to try out mcomaster without much fuss, I'd highly recommend using the vagrant setup that @lmello on github has contributed recently. It's really slick, and sets up everything you need, including redis, activemq, some mcollective nodes, and mcomaster. I've been meaning to add a note to the website recommending this.

Instructions are here:

https://github.com/ajf8/mcomaster/blob/master/VAGRANT.md

**Comment by stellatian** [comment]
From Alan:

agrant uses VirtualBox (by default) to quickly create virtual machines. For the whole mcomaster setup that takes 15-20 minutes on my laptop, but you wait and don't have to do anything.

I created puppet modules for mcomaster (https://github.com/ajf8/mcomaster/tree/master/tools/puppet/modules), which you may find useful. The vagrant install uses these. Of course you can use them outside of vagrant, but YMMV.

So using the Vagrant setup won't affect or use any existing activemq/mcollective you already have, but as I say it's great for trying mcomaster out. If you don't fancy using Vagrant that's no problem, I'll try to answer your questions below...

1) If you want to use the el/centos6 RPMs I made, you'll need to install the ruby193 SCL (software collection library) using the instructions provided, whether you have ruby 1.9 already or not. If you're not using the RPMs, install ruby 1.9 through whatever means you like, and also install bundler (via gem or whatever).

2) You will probably need to "gem install redis" whether you use the RPMs or not, on the host that handles registration data. This is because it needs to be installed into the same ruby as mcollective. If you're using the SCL with the mcomaster RPM, that's probably a different installation of ruby to mcollective.

3) I did mean client.cfg, not client.yml, I'll fix that. And yes, some of the same settings (for redis) are set in client.cfg and server.cfg.

4) Yes, they are seperate interfaces. If you're using the RPM and the init script, the port can be changed in /etc/sysconfig/mcomaster. If not and you're starting it through "rails server", use the -p option.

**Comment by stellatian** [comment]
Hi Alan,

Thank you for the detail reply. It is more clear now.

Yes, I plan to use the el/centos6 RPMs of mcomaster. I am using Red Hat Linux 6.5. Let me confirm if I understand correctly:
1. So I need to install redis.  Which method should I use to install redis? You said "gem install redis", but in your last year's discussion in an issue (https://github.com/ajf8/mcomaster/issues/1), you mentioned "yum install redis" and "service redis start" as root.  Just want to confirm which is the correct method?
2. So I need to to first install bundler by "gem install bundler". Then your RPM can use bundler to install dependencies.
3. So I need to install the ruby193 SCL (software collection library), but the instructions you provided only talks about "install the SCL repository". After the SCL repository is installed, you don't mention to install SCL package. Or maybe it will be called by the install of mcomaster package? Please clarify.
   
   Install the SCL repository
   Install the mcomaster repository
   Install mcomaster packages
4. The install doc talks about two types of install, "Install mcomaster from CentOS/RHEL 6 RPM" and "Install mcomaster (from source)". The last 3 steps listed under ""Install mcomaster (from source)" seems also needed for "Install mcomaster from CentOS/RHEL 6 RPM"?
   
   compile assets
   to start
   alternatively, start with SSL
5. So to use a different port other than 3000 which is using by my Dashboard, I will change the mcomaster port in /etc/sysconfig/mcomaster.

Thanks,
Stella

**Comment by ajf8** [comment]
Hi,

Glad it explained a few things... It's good to get feedback about the install document, as only a few people have ever done so and I'm sure some it can be made clearer.

1) You need both the redis server (which is probably by some RPM repository) and runs in a daemon process, and the gem, so we can connect to redis from ruby. It really is quite simple on el6 (EPEL I think) to get the server running, just yum install and then start the service.

Because the discovery and registration is done with redis it's needed in the same Ruby runtime as mcollective.

4) The "install from source" and "install from RPM" are supposed to be exclusive/seperate.

2) Not if you're installing from RPM. It has dependencies on the bundler RPMs.

3) Similarly, RPM dependencies will install them, if the repository is setup.

5) Right.

**Comment by stellatian** [comment]
Hi Alan,

I have been waiting for your final words before I start the install :)  Glad to see almost all my questions are anwsered. Here is the last question that I am confused.

4) The "install from source" and "install from RPM" are supposed to be exclusive/seperate.

However, for "install from RPM", the last step is "And a first admin user". You don't even have steps to compile assets and start mcomaster in ""install from RPM" section. Is this correct???

Hope this is the last question before I jump to install :)

thanks,
Stella

**Comment by ajf8** [comment]
Yes, they are seperate. Compiling assets is done as part of the build process for the RPM. From source requires a few more steps than from RPM.

**Comment by stellatian** [comment]
OK, I understand that compiling assets can be part of the RPM install process, but how about start mcomaster? If I install from RPM, I don't even need to start mcomaster manually? I assume the RPM install will also lay down /etc/init.d/mcomaster, then I can use "mcomaster start/stop/status"? 

Excited...almost ready to install mcomaster....

**Comment by ajf8** [comment]
There is an init script you will need to use. It's not started as part of the installation I think.

"service mcomaster start"

**Comment by stellatian** [comment]
Hi Alan,

I installed mcomaster this morning and everything works like a charm. I don't encounter any problem. The mcomaster gui looks as nice as the Puppet Dashboard Live Management! 

One more questions: how many nodes can your mcomaster handle? If I have about 300 nodes, is it ok? 

Many thanks!  Have a good weekend!

Stella

**Comment by lmello** [comment]
Stellatian, 

It is great that you had success installing and running it. 

You should not have any performance problem, because in this scale it won't be affected by the number of nodes. 

It could be affected by the number of simultaneous people accessing the application. (you should scale just like any other rails application) 

 The actions are async and pretty lightweight because of mcollective. 

I use mcollective currently for this number of nodes, and plan on using it on more than 2000 in 6 months. 

There is people using mcollective to manage more than 10000 nodes, it have a high performance architecture, and mcomaster is "just" a frontend to it. 

this is my understanding, maybe @ajf8  could enlighten us more on that.

**Comment by stellatian** [comment]
Imello,

Thank you for the reply. Glad to hear that mcomaster can be used on many nodes. Simultaneous accessing is not a problem for me, because only me and another person will admin this puppet/mcollective/mcomaster environment.

When you say that you use mcollective currently for this number of nodes, you mean you use mcollective command line? Or use mcomaster ui? Or a combination of both? 

thanks,
Stella

**Comment by ajf8** [comment]
I think it should scale to a reasonably large number of nodes, but to be honest I don't really do much testing with large numbers of nodes. I would be interested to know how well it works.

mcomaster takes the results from mcollective in a thread, and they get put onto queues in redis which the client streams back. That should be fast I hope. 

I would imagine a very large number of nodes could be slow if the responses are large, as they all get stored on the client side. It could potentially do lazy fetches of results from the queue if that's ever a problem.
