### ISSUE TITLE
No Filter for Nodes?

### ISSUE THREAD

**Issue by stellatian** [ajf8/mcomaster#25]
Hi Alan,

I have mcomaster up and running. I am comparing it with Enterprise Puppet Dashboard Live Management. Most the same (good job!), except that I can't find "Node Filter" which allows me to filter node by name, class or fact, and then select the nodes for my next action.

For example, I can only select one node from the left list, and then "runonce" on this node. 
If I want to "runonce" on all the nodes whose hostname starts with "test", I can't.

Do I miss any configuration or it is a feature not implemented yet?

Thanks,
Stella

**Comment by ajf8** [comment]
If you navigate to an action through a host, the request is limited to that host. If you need filters, navigate through the agent.

In the discovery filters tab, "add identity filter", and use a regex string like "/^test/"

**Comment by ajf8** [comment]
Closing this as I believe it to be implemented already.

There's requests open for "OR" expressions which I plan to do. Also to improve the usability of the stored filters sometime - the new, save, and delete buttons aren't very intuitive IMO.
