### ISSUE TITLE
Using specific client.cfg

### ISSUE THREAD

**Issue by lmello** [ajf8/mcomaster#26]
Hi 

There is anyway to specify one custom mcollective client.cfg configuration for mcomaster. 

I do not want to have a system wide mcollective client configuration. 

Maybe it is already implemented I just did not understand how to configure it. 

Could you provide one example, ao I could update the install documentation ?

**Comment by ajf8** [comment]
Hi Leonardo,

Wasn't supported previously but should have been. Very easy to add, I've just done it.

Set mcollective_config in your config/application.yml and it should get loaded on startup.

Let me know if you have any problems with. I'm going to be away for 1-2 weeks so will look at any issues when I return.

Thanks!
