### ISSUE TITLE
Looking for some assistance - Node not appearing

### ISSUE THREAD

**Issue by tek0011** [ajf8/mcomaster#34]
Hey.  Seems like a cool tool.  So I thought Id give it a go.  I have it all configured per your install guide.  I am able to connect via webui.  mco is working fine after the install.  However, I am not seeing any nodes show up on the mcomaster dashboard(if you want to call it that).

Not quite sure where to start.  Any help is greatly appreciated.  Thanks!

**Comment by lmello** [comment]
Check if your mcollective version is the same mcomaster require. Actually
the rpm require at least 2.6
Em 07/11/2014 17:48, "tek0011" notifications@github.com escreveu:

**Comment by tek0011** [comment]
The Marionette Collective version 2.6.1

**Comment by tek0011** [comment]
Any other thoughts?

**Comment by tek0011** [comment]
Bump.  Still working on this.

**Comment by lmello** [comment]
Please attach your mcollective server.cfg and client.cfg.

Also look for errors at  /var/log/mcollective.log and
/var/log/mcomaster/*.log
Em 13/11/2014 14:01, "tek0011" notifications@github.com escreveu:

**Comment by tek0011** [comment]
sure:

http://pastebin.com/bcyqeecS

Not much in the logs:  just looks like accesing users over and over:

  `User Load (0.3ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1  ORDER BY "users"."id" ASC LIMIT 1
Completed 200 OK in 3ms (Views: 0.2ms | ActiveRecord: 0.3ms)
Started GET "/nodes" for 172.31.100.214 at 2014-11-10 15:47:33 -0600
Processing by NodesController#index as JSON`

`User Load (0.4ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1  ORDER BY "users"."id" ASC LIMIT 1
Completed 200 OK in 3ms (Views: 0.2ms | ActiveRecord: 0.4ms)`

Interesting, from mcollective.log:

`E, [2014-11-07T13:46:15.795243 #3043] ERROR -- : pluginmanager.rb:171:in 'loadclass' Failed to load MCollective::Agent::Registration: no such file to load -- redis`
`E, [2014-11-07T13:46:15.800084 #3043] ERROR -- : agents.rb:71:in 'loadagent' Loading agent registration failed: no such file to load -- redis`

**Comment by tek0011** [comment]
bump

**Comment by tek0011** [comment]
Do you have a forums or a google group?  Somewhere that provides assistance?  I tried posting to stackoverflow, but the chances of finding someone else that has used this is slim to none.  I decided to try mcomaster over kermit, but I will have to go there if there is no support here.
Thanks.

**Comment by lyhsoft** [comment]
Do you have the mcollective-public-servers.pem file in the '/etc/mcollective/clients' directory?

**Comment by ajf8** [comment]
Hi there,

Sorry for delay responding.

mcomaster runs in the bundler environment which has this redis gem, but your mcollective daemon responsible for collecting up node registrations doesn't appear to have it available. If you used packages from puppetlabs or your distribution, it's probably the system "default" ruby. It should just be a case of doing "/usr/bin/gem install redis" (there's a note about this in the install guide I think).

**Comment by tek0011** [comment]
@lyhsoft - No I do not see any files in the /etc/mcollective/ssl/clients directory.  Nor do I find it anywhere on the server.  All .pem files are in /var/lib/puppet/ssl/.
@ajf8 - I did confirm that redis gem was missing.  Installed it, restarted mcollective, mcomaster, redis. 

Nodes still not populating in to mcomaster.  Thanks for your help getting this resolved.

**Comment by tek0011** [comment]
I may very well be having other issues now, as mco ping is not finding any hosts aside from the master/server its running on.

I have confirmed that redis.conf states port 6379 as well as server.cfg:
`plugin.redis.port = 6379`

mcolog:
`
I, [2014-11-24T07:38:28.167601 #28519]  INFO -- : runner.rb:104:in`main_loop' Exiting after signal: SIGTERM
I, [2014-11-24T07:38:29.840791 #25672]  INFO -- : config.rb:160:in `loadconfig' The Marionette Collective version 2.6.1 started by /usr/sbin/mcollectived using config file /etc/mcollective/server.cfg
I, [2014-11-24T07:38:29.841052 #25672]  INFO -- : mcollectived:52 The Marionette Collective 2.6.1 started logging at info level
I, [2014-11-24T07:38:29.887938 #25675]  INFO -- : activemq.rb:288:in`connection_headers' Connecting without STOMP 1.1 heartbeats, if you are using ActiveMQ 5.8 or newer consider setting plugin.activemq.heartbeat_interval
I, [2014-11-24T07:38:29.889287 #25675]  INFO -- : activemq.rb:114:in `on_connecting' TCP Connection attempt 0 to stomp://mcollective@puppet.foundry.test:61613
I, [2014-11-24T07:38:29.927814 #25675]  INFO -- : activemq.rb:119:in`on_connected' Connected to stomp://mcollective@puppet.foundry.test:61613
E, [2014-11-24T07:38:30.845163 #25675] ERROR -- : registration.rb:41:in `handlemsg' /usr/lib/ruby/gems/1.8/gems/redis-3.1.0/lib/redis/client.rb:309:in`establish_connection': Redis::CannotConnectError: Error connecting to Redis on puppet.foundry.test:6379 (ECONNREFUSED)
E, [2014-11-24T07:43:30.866478 #25675] ERROR -- : registration.rb:41:in `handlemsg' /usr/lib/ruby/gems/1.8/gems/redis-3.1.0/lib/redis/client.rb:309:in`establish_connection': Redis::CannotConnectError: Error connecting to Redis on puppet.foundry.test:6379 (ECONNREFUSED)
E, [2014-11-24T07:48:30.911745 #25675] ERROR -- : registration.rb:41:in `handlemsg' /usr/lib/ruby/gems/1.8/gems/redis-3.1.0/lib/redis/client.rb:309:in`establish_connection': Redis::CannotConnectError: Error connecting to Redis on puppet.foundry.test:6379 (ECONNREFUSED)
E, [2014-11-24T07:53:30.900048 #25675] ERROR -- : registration.rb:41:in `handlemsg' /usr/lib/ruby/gems/1.8/gems/redis-3.1.0/lib/redis/client.rb:309:in`establish_connection': Redis::CannotConnectError: Error connecting to Redis on puppet.foundry.test:6379 (ECONNREFUSED)
E, [2014-11-24T07:58:30.905841 #25675] ERROR -- : registration.rb:41:in `handlemsg' /usr/lib/ruby/gems/1.8/gems/redis-3.1.0/lib/redis/client.rb:309:in`establish_connection': Redis::CannotConnectError: Error connecting to Redis on puppet.foundry.test:6379 (ECONNREFUSED)
I, [2014-11-24T08:02:34.580432 #25675]  INFO -- : runner.rb:104:in `main_loop' Exiting after signal: SIGTERM
I, [2014-11-24T08:02:35.292765 #26762]  INFO -- : config.rb:160:in`loadconfig' The Marionette Collective version 2.6.1 started by /usr/sbin/mcollectived using config file /etc/mcollective/server.cfg
I, [2014-11-24T08:02:35.293268 #26762]  INFO -- : mcollectived:52 The Marionette Collective 2.6.1 started logging at info level
I, [2014-11-24T08:02:35.335867 #26767]  INFO -- : activemq.rb:288:in `connection_headers' Connecting without STOMP 1.1 heartbeats, if you are using ActiveMQ 5.8 or newer consider setting plugin.activemq.heartbeat_interval
I, [2014-11-24T08:02:35.339901 #26767]  INFO -- : activemq.rb:114:in`on_connecting' TCP Connection attempt 0 to stomp://mcollective@puppet.foundry.test:61613
I, [2014-11-24T08:02:35.408844 #26767]  INFO -- : activemq.rb:119:in `on_connected' Connected to stomp://mcollective@puppet.foundry.test:61613
E, [2014-11-24T08:02:36.231671 #26767] ERROR -- : registration.rb:41:in`handlemsg' /usr/lib/ruby/gems/1.8/gems/redis-3.1.0/lib/redis/client.rb:309:in `establish_connection': Redis::CannotConnectError: Error connecting to Redis on puppet.foundry.test:6379 (ECONNREFUSED)
E, [2014-11-24T08:07:36.248401 #26767] ERROR -- : registration.rb:41:in`handlemsg' /usr/lib/ruby/gems/1.8/gems/redis-3.1.0/lib/redis/client.rb:309:in `establish_connection': Redis::CannotConnectError: Error connecting to Redis on puppet.foundry.test:6379 (ECONNREFUSED)
E, [2014-11-24T08:12:36.253645 #26767] ERROR -- : registration.rb:41:in`handlemsg' /usr/lib/ruby/gems/1.8/gems/redis-3.1.0/lib/redis/client.rb:309:in `establish_connection': Redis::CannotConnectError: Error connecting to Redis on puppet.foundry.test:6379 (ECONNREFUSED)
`

**Comment by tek0011** [comment]
fixed mcollective, it is now pinging correctly to nodes.  The client.cfg was not setup for windows correctly.  I do still however get the:
`E, [2014-11-24T09:48:58.344551 #26767] ERROR -- : registration.rb:41:in 'handlemsg' /usr/lib/ruby/gems/1.8/gems/redis-3.1.0/lib/redis/client.rb:309:in 'establish_connection': Redis::CannotConnectError: Error connecting to Redis on puppet.foundry.test:6379 (ECONNREFUSED)`

**Comment by tek0011** [comment]
I figured out why things weren't working.  The client.cfg was not copying over correctly, so it was getting over written with wrong settings.  Nodes are populating now.  However, what determines if a node has a puppet agent or only a rpcutil agent?  Right now only the master/server itself is showing a puppet agent, where I can disable or enable it. 
The other nodes only report the rpcutil, not allowing me to disable/enable puppet.

Thanks a ton for pointing me int he right direction to get this working.

http://i.imgur.com/48kvWmv.png

**Comment by ajf8** [comment]
No problem :)

It's the nodes registration which determines this, which is sent up and then collected into redis. If you can see the agent on any server that's good, because it means the DDL is working on your mcomaster host at least.

Have you checked the mcollective node log to ensure it's really loaded the agent successfully (eg. not failing to load the puppet library etc)? Does it work from mco rpc?

with redis-cli you can check what agents a host has:

redis 127.0.0.1:6379> smembers "mcollective::nodeagents::hostnamehere"
1) "discovery"
2) "puppet"
3) "registration"
4) "service"
5) "shell"
6) "rpcutil"
7) "nettest"

**Comment by tek0011** [comment]
Well I am able to run that command and determine it only shows:

1) "rpcutil"
2) "discovery"

Sorry, the rest to me is confusing.  I am poking around trying to figure out where the registration info is set.  Its only my 4th week on puppet and 5th week on Linux :(

Edit:  I see where server.cfg is calling out meta.rb though for registration. a

**Comment by ajf8** [comment]
Most likely the agent is not loading on those nodes.

Take a look at the mcollective log on the hosts where you're expecing to see this agent. For me it's /var/log/mcollective.log

You should see something like this, for a successful loading of the agent, but I suspect there will be an  error.

debug 2014/11/24 20:35:34: agents.rb:104:in `block in findagentfile' Found puppet at /usr/libexec/mcollective/mcollective/agent/puppet.rb
debug 2014/11/24 20:35:34: pluginmanager.rb:167:in`loadclass' Loading MCollective::Agent::Puppet from mcollective/agent/puppet.rb
debug 2014/11/24 20:35:34: pluginmanager.rb:44:in `<<' Registering plugin puppet_agent with class MCollective::Agent::Puppet single_instance: false
debug 2014/11/24 20:35:34: pluginmanager.rb:88:in`[]' Returning new plugin puppet_agent with class MCollective::Agent::Puppet
debug 2014/11/24 20:35:34: cache.rb:117:in `block in ttl' Cache miss on 'ddl' key 'agent/puppet'
debug 2014/11/24 20:35:34: base.rb:94:in`block in findddlfile' Found puppet ddl at /usr/libexec/mcollective/mcollective/agent/puppet.ddl

**Comment by tek0011** [comment]
I see facts and activeq.  I do not see MCollective::Agent::Puppet called anywhere.

`D, [2014-11-24T16:04:22.847303 #1784] DEBUG -- : pluginmanager.rb:83:in`[]' Returning cached plugin facts_plugin with class MCollective::Facts::Yaml_facts
D, [2014-11-24T16:04:22.847303 #1784] DEBUG -- : base.rb:30:in `block in get_fact' Resetting facter cache, now: 1416866662 last-known-good: 1416866062
D, [2014-11-24T16:04:22.847303 #1784] DEBUG -- : pluginmanager.rb:83:in`[]' Returning cached plugin security_plugin with class MCollective::Security::Psk
D, [2014-11-24T16:04:22.847303 #1784] DEBUG -- : base.rb:178:in `create_request' Encoding a request for agent 'registration' in collective mcollective with request id 92801bad5050571baa011e47506877be
D, [2014-11-24T16:04:22.847303 #1784] DEBUG -- : psk.rb:98:in`callerid' Setting callerid to uid=0 based on callertype=uid
D, [2014-11-24T16:04:22.847303 #1784] DEBUG -- : base.rb:70:in `publish' Sending registration 92801bad5050571baa011e47506877be to collective mcollective
D, [2014-11-24T16:04:22.847303 #1784] DEBUG -- : pluginmanager.rb:83:in`[]' Returning cached plugin connector_plugin with class MCollective::Connector::Activemq
D, [2014-11-24T16:04:22.847303 #1784] DEBUG -- : activemq.rb:408:in `publish' Sending a broadcast message to ActiveMQ target '/topic/mcollective.registration.agent' with headers '{"timestamp"=>"1416866662000", "expires"=>"1416866732000", "reply-to"=>"/queue/mcollective.reply.puppetagent1_1784"}'
`

**Comment by ajf8** [comment]
Is it definitely installed and readable under your agents directory? Probably /usr/libexec/mcollective/mcollective/agent

**Comment by tek0011** [comment]
Ok.  So.  My first BAD experience with puppet.   I forgot I told the Puppet Agent to Ensure running, so as I was testing out new configs, unknowningly puppet was coming back in and overwriting them.  What a great experience.  So, now that I have the configs set correctly (I found puppet removing /plugins/mcollective/agent/registration.rb was getting removed..  YAY.

So I replaced it, and corrected te server.cfg and batch files.  

I am now getting:
`D, [2014-11-24T16:55:04.023618 #296] DEBUG -- : pluginmanager.rb:80:in`[]' Returning new plugin discovery_agent with class MCollective::Agent::Discovery
D, [2014-11-24T16:55:04.023618 #296] DEBUG -- : pluginmanager.rb:83:in `[]' Returning cached plugin connector_plugin with class MCollective::Connector::Activemq
D, [2014-11-24T16:55:04.023618 #296] DEBUG -- : activemq.rb:419:in`subscribe' Subscribing to /topic/mcollective.discovery.agent with headers {}
D, [2014-11-24T16:55:04.023618 #296] DEBUG -- : agents.rb:104:in `block in findagentfile' Found puppet at c:\marionette-collective\plugins/mcollective/agent/puppet.rb
D, [2014-11-24T16:55:04.023618 #296] DEBUG -- : pluginmanager.rb:167:in`loadclass' Loading MCollective::Agent::Puppet from mcollective/agent/puppet.rb
D, [2014-11-24T16:55:04.054865 #296] DEBUG -- : pluginmanager.rb:44:in `<<' Registering plugin puppet_agent with class MCollective::Agent::Puppet single_instance: false
D, [2014-11-24T16:55:04.054865 #296] DEBUG -- : pluginmanager.rb:88:in`[]' Returning new plugin puppet_agent with class MCollective::Agent::Puppet
D, [2014-11-24T16:55:04.054865 #296] DEBUG -- : cache.rb:117:in `block in ttl' Cache miss on 'ddl' key 'agent/puppet'
D, [2014-11-24T16:55:04.070490 #296] DEBUG -- : base.rb:94:in`block in findddlfile' Found puppet ddl at c:\marionette-collective\plugins/mcollective/agent/puppet.ddl
W, [2014-11-24T16:55:04.070490 #296]  WARN -- : base.rb:104:in `validate_requirements' DDL requirements validation being skipped in development
E, [2014-11-24T16:55:04.070490 #296] ERROR -- : agents.rb:71:in`rescue in loadagent' Loading agent puppet failed: Could not create instance of plugin MCollective::Agent::Puppet: cannot load such file -- puppet`

This is just an update, I have not began to look in to this yet.  But I will.

Now.

**Comment by ajf8** [comment]
Good luck... That error means that the mcollective puppet agent cannot load the puppet ruby library it requires.

I don't really have any experience of puppet/mco on Windows so can't really help here. They need to be  using or installed into the same ruby install, I guess.

**Comment by tek0011** [comment]
I was able to resolve this by putting the following in Environments:

`PATH` added => `C:\Program Files\Puppet Labs\Puppet\sys\ruby\bin` in order to point to the puppet version of Ruby (I never installed Ruby for windows, just using puppets version it comes with.

then

`RUBYLIB` => `C:\Program Files\Puppet Labs\Puppet\puppet\lib;C:\Program Files\Puppet Labs\Puppet\facter\lib;C:\Program Files\Puppet Labs\Puppet\hiera\lib`

I had to add facter, puppet and hieria.  I now have puppet control for windows servers in mcomaster. 

Side question.  I see this in the debugs as well.  Any ideas?  Everything seems to be working so not sure if this has any meaning.  

`E, [2014-11-25T06:41:10.191638 #2152] ERROR -- : pluginmanager.rb:171:in 'rescue in loadclass' Failed to load MCollective::Agent::Registration: cannot load such file -- redis`

`E, [2014-11-25T06:41:10.191638 #2152] ERROR -- : agents.rb:71:in 'rescue in loadagent' Loading agent registration failed: cannot load such file -- redis`

Thanks again so much for your help.

**Comment by tek0011** [comment]
I ran:

`gem install redis` on the windows server, error seems to be gone.  Would that have done it?

**Comment by ajf8** [comment]
Hi,

You're welcome.

There shouldn't be any need to install the registration agent on your "regular" hosts, or for them to interact with redis. You only need the registration agent on one agent (or more if you want high availability for that), which is responsible for collecting up registration data into redis. For most people (and you from what I gather), that would be the mcomaster host.

**Comment by tek0011** [comment]
Ok this is all starting to make sense.  I hope if anyone else tries to use mcomaster with mcollective windows nodes, that this thread finds them and helps.
Thanks very much for your help with this.  Its all very new to me, but its starting to make sense.  

Great help, great work.
