### ISSUE TITLE
Saved filters

### ISSUE THREAD

**Issue by epleterte** [ajf8/mcomaster#4]
It would be cool to be able choose from a predefined set of filters for those recurring actions.
Pick some filters, then add to your list of saved filters.
This would improve daily workflow as well as give the app a more personal feel ;)

**Comment by ajf8** [comment]
Totally agree here, I had it in mind myself actually. WIll probably implement soon.

**Comment by epleterte** [comment]
Sounds good! :)

**Comment by ajf8** [comment]
I've pushed this feature, might be a little rough around the edges but it seems to work for me. a rake db:migrate will be needed.

**Comment by ajf8** [comment]
This has been around for a while now. There's another request for OR expressions which I'm planning to implement.
