### ISSUE TITLE
Result/nodelist export function

### ISSUE THREAD

**Issue by epleterte** [ajf8/mcomaster#5]
MCollective is good for taking out live reports. You can write a bunch of cool reporting modules if you want. More often, however, I'm asked to help someone get an overview or ensure a status - they'd like a quick report for themselves. I think it would be nice if the report table returned could be exported directly as a csv (and if you feel like it, other formats as well). 

As a second convenience export function I'd like to suggest being able to export the list of nodes returning 'successful' or the list of nodes returning 'failed' to a simple one-node-per-line-txt-format.
This is not really necessary, but would make it easy to go back and forth between WebUI and CLI usage. I.e. I'd like to build complex filters using the web interface, but would like to use the responding nodes in a shell script using the _mco --nodes nodes.txt_ feature, or maybe for something completely different.

**Comment by ajf8** [comment]
Another good suggestion, thanks :)

**Comment by ajf8** [comment]
Pushed simple CSV export of results earlier (link bottom right of results table), let me know how it works.

Couldn't find a simple JS CSV generator I could reuse, so wrote one myself with some basic escaping which still needs testing.

I'll add JSON export and maybe filtering another time.

**Comment by epleterte** [comment]
Awesome! Will test when I can find the time! :)
