### ISSUE TITLE
Issue with puppet Agent and splashlimit parameter

### ISSUE THREAD

**Issue by Marcel-Wittwer** [ajf8/mcomaster#6]
Hey,

I recently installed the mcomaster on CentOS 6.4 and so far it's been working great. Now I realized that if I try to trigger a "runonce" via the puppet Agent the field for splashlimit is printing an Error:

Error
"Cannot validate input splaylimit: value should be a number"

It doesn't matter whether I set "Splay" to false or true with a value for splashlimit (e.g. 30). On having a look into the production.log the parameters seem to get the right values..

without splay:

"Received a request, parameters: {"filter":{},"args":{"force":false,"server":"","tags":"","noop":true,"splay":false,"splaylimit":"","environment":"production"}}"

with splay and splaylimit:

"Received a request, parameters: {"filter":{},"args":{"force":false,"server":"","tags":"","noop":true,"splay":true,"splaylimit":"30","environment":"production"}}"

Is there anything I might did wrong?

Thanks in advance!

**Comment by ajf8** [comment]
Hi, 

I think I see the issue, mcomaster is sending the number as a string. Should be an easy fix, will do soon.

**Comment by ajf8** [comment]
Please test

**Comment by ajf8** [comment]
If you have tried it already, I found the fix didn't quite work. Hopefully fixed now.
