### ISSUE TITLE
nettest agent connect/port

### ISSUE THREAD

**Issue by PsychoSid** [ajf8/mcomaster#7]
Hello,

When trying to use the nettest connect agent through mcomaster the port response states that it must be an integer even if I use 80, or 443 for instance.

![image](https://f.cloud.github.com/assets/2253671/1095799/d9d5eb96-16f0-11e3-86ca-0ca2d4fd6140.png)

**Comment by ajf8** [comment]
Thanks for the report. It was sending it as a string not an integer, I think I've fixed it now. The nettest plugin works for me.

**Comment by PsychoSid** [comment]
Confirmed. Thanks.
