### ISSUE TITLE
Asset compilation issue

### ISSUE THREAD

**Issue by ReplicaObscura** [ajf8/mcomaster#9]
Assets are precompiled with a checksum in their filename for me, but the images used by mcomaster (such as node.png, agent.png, collective.png, etc) don't have a checksum in the name so they are broken.

Is there something I need to do to either make sure the references to the images include the checksum, or that assets are compiled without the checksum in the filename?

**Comment by matthewbarr** [comment]
I don't know enough about rails to trouble shoot this.  I've got a vagrant box w/ ubuntu 12.04 that's got the same issue.  For some reason the images aren't getting the hash appended, but the CSS & JS seem to get the right hash.

**Comment by ajf8** [comment]
@lmello has kindly fixed this, doing it properly, using the rails helpers in the templates for the URLs :)
